#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed May 27 17:49:30 PDT 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 87f7a14d83ae4b6f801a61a53c903829 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot LogicBoy_behav xil_defaultlib.LogicBoy xil_defaultlib.glbl -log elaborate.log"
xelab -wto 87f7a14d83ae4b6f801a61a53c903829 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot LogicBoy_behav xil_defaultlib.LogicBoy xil_defaultlib.glbl -log elaborate.log

