# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/linuxpack/Vivado/LogicBoy/LogicBoy.cache/wt [current_project]
set_property parent.project_path /home/linuxpack/Vivado/LogicBoy/LogicBoy.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/linuxpack/Vivado/LogicBoy/LogicBoy.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/ALU.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/Graphics/BitmapToVga.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/ButtonDebouncer.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/General Modules/CCounter.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/General Modules/CLRegister.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/CPU.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/General Modules/Debounce.sv}
  /home/linuxpack/Vivado/LogicBoy/LogicBoy.srcs/sources_1/new/DrawButtons.sv
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/Graphics/DrawSprites.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/Graphics/DrawTileMap.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/Graphics/DrawWindowLayer.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/GeneralRam.sv}
  /home/linuxpack/Vivado/LogicBoy/LogicBoy.srcs/sources_1/new/InputReader.sv
  /home/linuxpack/Vivado/LogicBoy/LogicBoy.srcs/sources_1/new/MemoryMultiplexer.sv
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/Graphics/PixelProcesser.sv}
  /home/linuxpack/Vivado/LogicBoy/LogicBoy.srcs/sources_1/new/ReadOnlyMemory.sv
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/SevenSegmentControl.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/General Modules/ShiftRegister.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/Graphics/VideoRam.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/Graphics/VramRender.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/General Modules/mod_counter.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/ppTestModule.sv}
  {/home/linuxpack/Vivado/Game Boy HDL - Dec2/LogicBoy.sv}
}
read_verilog -library xil_defaultlib {{/home/linuxpack/Vivado/Game Boy HDL - Dec2/clk_generator.v}}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/linuxpack/Vivado/Game Boy HDL - Dec2/Constraints/nexys4_220.xdc}}
set_property used_in_implementation false [get_files {{/home/linuxpack/Vivado/Game Boy HDL - Dec2/Constraints/nexys4_220.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top LogicBoy -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LogicBoy.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LogicBoy_utilization_synth.rpt -pb LogicBoy_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
