webtalk_init -webtalk_dir /home/linuxpack/Vivado/LogicBoy/LogicBoy.sim/sim_1/behav/xsim/xsim.dir/LogicBoy_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 27 17:49:36 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "97747672-0f44-4d14-a827-efcc53335349" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "87f7a14d83ae4b6f801a61a53c903829" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "112" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A6-3650 APU with Radeon(tm) HD Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1023.966 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "28" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "514 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "49 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "623" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "69" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "4.93_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "299132_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2735929101 -regid "" -xml /home/linuxpack/Vivado/LogicBoy/LogicBoy.sim/sim_1/behav/xsim/xsim.dir/LogicBoy_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/linuxpack/Vivado/LogicBoy/LogicBoy.sim/sim_1/behav/xsim/xsim.dir/LogicBoy_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/linuxpack/Vivado/LogicBoy/LogicBoy.sim/sim_1/behav/xsim/xsim.dir/LogicBoy_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
