webtalk_init -webtalk_dir /home/linuxpack/Vivado/LogicBoy/LogicBoy.sim/sim_1/behav/xsim/xsim.dir/ppTestModule_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May 24 14:29:12 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "97747672-0f44-4d14-a827-efcc53335349" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "87f7a14d83ae4b6f801a61a53c903829" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A6-3650 APU with Radeon(tm) HD Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "892.565 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125692_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3511837787 -regid "" -xml /home/linuxpack/Vivado/LogicBoy/LogicBoy.sim/sim_1/behav/xsim/xsim.dir/ppTestModule_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/linuxpack/Vivado/LogicBoy/LogicBoy.sim/sim_1/behav/xsim/xsim.dir/ppTestModule_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/linuxpack/Vivado/LogicBoy/LogicBoy.sim/sim_1/behav/xsim/xsim.dir/ppTestModule_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
